spring:
  datasource:
      url: jdbc:mysql://39.107.230.237:3306/manage?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 285310
mybatis:
   mapperLocations: classpath:/mapper/*.xml
